# Generated by Django 4.2.7 on 2023-11-21 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='passby',
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.IntegerField(default=1166),
        ),
        migrations.AddField(
            model_name='student',
            name='passed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
